# Generated by Django 2.0.5 on 2018-05-23 00:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_id', models.TextField(unique=True)),
                ('created_time', models.DateTimeField()),
                ('user_has_liked', models.BooleanField()),
                ('likes', models.IntegerField()),
                ('type', models.TextField()),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='InstagramTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='InstagramUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_id', models.CharField(max_length=20, unique=True)),
                ('username', models.TextField()),
                ('profile_picture', models.TextField()),
                ('full_name', models.TextField()),
                ('bio', models.TextField()),
                ('website', models.URLField(blank=True)),
                ('is_business', models.BooleanField()),
                ('counts_media', models.IntegerField()),
                ('counts_follows', models.IntegerField()),
                ('counts_followed_by', models.IntegerField()),
                ('posts', models.ManyToManyField(to='api.InstagramPost')),
            ],
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='tags',
            field=models.ManyToManyField(blank=True, to='api.InstagramTag'),
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.InstagramUser'),
        ),
    ]
