# Generated by Django 2.0.5 on 2018-05-22 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramPost',
            fields=[
                ('id', models.TextField(primary_key=True, serialize=False)),
                ('created_time', models.DateTimeField()),
                ('user_has_liked', models.BooleanField()),
                ('likes', models.IntegerField()),
                ('type', models.TextField()),
                ('link', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='InstagramUser',
            fields=[
                ('id', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('username', models.TextField()),
                ('profile_picture', models.TextField()),
                ('full_name', models.TextField()),
                ('bio', models.TextField()),
                ('website', models.URLField(blank=True)),
                ('is_business', models.BooleanField()),
                ('counts_media', models.IntegerField()),
                ('counts_follows', models.IntegerField()),
                ('counts_followed_by', models.IntegerField()),
                ('posts', models.ManyToManyField(to='api.InstagramPost')),
            ],
        ),
    ]
