# Generated by Django 2.0.5 on 2018-05-22 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial database model'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagrampost',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='api.InstagramUser'),
            preserve_default=False,
        ),
    ]
