# Generated by Django 2.0.5 on 2018-05-24 21:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_Added instagram images model'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstagramCaption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instagram_id', models.TextField(unique=True)),
                ('text', models.TextField()),
                ('created_time', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.InstagramUser')),
            ],
        ),
        migrations.AddField(
            model_name='instagrampost',
            name='caption',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='api.InstagramCaption'),
            preserve_default=False,
        ),
    ]
