# Generated by Django 2.0.5 on 2018-05-24 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_Added instagram caption model;\n'),
    ]

    operations = [
        migrations.AddField(
            model_name='instagrampost',
            name='comments',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
