# Generated by Django 2.0.5 on 2018-05-24 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_Added comments field to IGPost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagrampost',
            name='caption',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.InstagramCaption'),
        ),
        migrations.AlterField(
            model_name='instagrampost',
            name='images',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='api.InstagramImages'),
        ),
    ]
