# Generated by Django 2.0.5 on 2018-05-24 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_Allowed caption and image of IG post to be nullable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagrampost',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.InstagramUser'),
        ),
    ]
