# Generated by Django 2.0.5 on 2018-05-24 23:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_User delete cascade rule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instagramcaption',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.InstagramUser'),
        ),
    ]
